# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13BkTfN55SYw1SV_P2g7YHLiqX8k7TfeS
"""

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from recommend import recommend_product

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Change this to your domain if needed
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.post("/recommend")
async def recommend_api(request: Request):
    body = await request.json()
    salary = body.get("salary")
    budget = body.get("budget")
    brand_query = body.get("brand_query")
    category_input = body.get("category_input")
    selected_models = body.get("selected_models", [])

    result = recommend_product(
        salary=salary,
        budget=budget,
        brand_query=brand_query,
        category_input=category_input,
        selected_models=selected_models,
        verbose=False
    )
    return result